version : '3'
services:
  crm:
    build: CRM
    links: 
      - crm.data

  crm.data:
    image: postgres:alpine
    restart: always

  adminer:
    image: adminer

  rabbitmq:
    image: rabbitmq:3.6-management-alpine