version : '3'
services:
  crm:
    ports:
      - "5100:8080"
    environment:
      - 'SPRING_APPLICATION_JSON={
        "spring": {
          "datasource": {
            "username": "crm",
            "password": "Str0ngP@ssW0rd",
            "url": "jdbc:postgresql://crm.data:5432/crm"
          },
          "jpa": {
            "hibernate": {
              "ddl-auto": "create-drop"
            }
          },
          "rabbitmq": {
            "host": "rabbitmq",
            "username": "guest",
            "password": "guest"
          }
        }
      }'

  crm.data:
    environment:
      - POSTGRES_PASSWORD=Str0ngP@ssW0rd
      - POSTGRES_USER=crm

  orchestrator:
    ports:
      - "5101:8080"
    environment:
      - 'SPRING_APPLICATION_JSON={
        "spring": {
          "datasource": {
            "username": "orchestrator",
            "password": "Str0ngP@ssW0rd",
            "url": "jdbc:postgresql://orchestrator.data:5432/orchestrator"
          },
          "jpa": {
            "hibernate": {
              "ddl-auto": "create-drop"
            }
          },
          "rabbitmq": {
            "host": "rabbitmq",
            "username": "guest",
            "password": "guest"
          }
        }
      }'

  orchestrator.data:
    environment:
      - POSTGRES_PASSWORD=Str0ngP@ssW0rd
      - POSTGRES_USER=orchestrator

  adminer:
    ports:
      - "6100:8080"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"